name: Sync WIT API to `pumpkin-plugin-wit`

on:
  push:
    branches:
      - master
    paths:
      - "pumpkin-plugin-wit/**"

jobs:
  sync-wit:
    runs-on: ubuntu-latest
    steps:
      - name: Create app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          # required
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: QuantumSegfault
          repositories: file-sync-test-other

      - name: Get app user ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Authenticate as the app/bot
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          gh auth setup-git
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: main-repo
          sparse-checkout: pumpkin-plugin-wit

      - name: Checkout WIT repo
        uses: actions/checkout@v4
        with:
          repository: "PumpkinMC/pumpkin-plugin-wit"
          token: ${{ steps.app-token.outputs.token }}
          path: wit-repo

      - name: Sync and commit changes
        run: |
          cd wit-repo
          rsync -av --delete --exclude='.git' --exclude='.github' ../main-repo/pumpkin-plugin-wit/ .

          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "sync: update WIT to PumpkinMC/Pumpkin@${{ github.sha }}"
            git push origin master
          else
            echo "No changes detected in WIT files. Skipping push."
          fi
